/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/coin.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh name="Coinv2" geometry={nodes.Coinv2.geometry} material={materials.Gold} position={[-0.01, 3.88, 0]} />
    </group>
  )
}

useGLTF.preload('/coin.glb')
